spring:
  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liiVf5N5o6OGNK0w
            clientSecret: 4d864e7c65d4ce6abf8e2e0a82d0e291bf512ea2

server:
  port: 8080
